name: gwa
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotlipy=0.7.0
  - ca-certificates=2022.5.18.1
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - click=8.1.3
  - colorama=0.4.4
  - cryptography=35.0.0
  - dataclasses=0.8
  - filelock=3.7.0
  - freetype=2.10.4
  - future=0.18.2
  - huggingface_hub=0.6.0
  - idna=3.3
  - igl=2.2.1
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - intel-openmp=2021.4.0
  - jbig=2.1
  - joblib=1.1.0
  - jpeg=9e
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.7
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libprotobuf=3.16.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - ncurses=6.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nltk=3.6.7
  - numpy=1.20.3
  - olefile=0.46
  - openssl=1.1.1o
  - packaging=21.3
  - pip=21.2.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.12
  - python_abi=3.9
  - pytorch=1.9.0
  - pyyaml=5.4.1
  - readline=8.1.2
  - regex=2022.3.15
  - requests=2.27.1
  - sacremoses=0.0.53
  - scikit-learn=0.23.2
  - scipy=1.5.3
  - sentence-transformers=2.2.0
  - sentencepiece=0.1.95
  - setuptools=61.2.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.38.3
  - threadpoolctl=3.1.0
  - tk=8.6.11
  - tokenizers=0.11.4
  - torchvision=0.9.1
  - tqdm=4.64.0
  - transformers=4.19.2
  - typing-extensions=4.2.0
  - typing_extensions=4.2.0
  - tzdata=2022a
  - urllib3=1.26.9
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - cycler==0.11.0
    - cython==0.29.30
    - fonttools==4.33.3
    - h5py==3.6.0
    - kiwisolver==1.4.2
    - matplotlib==3.5.2
    - networkx==2.8
    - pillow==9.1.1
    - python-dateutil==2.8.2
    - python-fcl==0.6.1
    - trimesh==3.12.0
