#NOTES:
# - create env: conda env create -f conda_pffdtd.yml
# - activate env: conda activate pffdtd
# - remove env: conda env remove -n pffdtd
name: pffdtd
channels:
  - numba
  - conda-forge
  - defaults
dependencies:
  - h5py >= 3.2.1
  - matplotlib >= 3.4.1
  - mayavi >= 4.7.2
  - memory_profiler >= 0.58.0
  - numba >= 0.53.0
  - numpy >= 1.20.1
  - polyscope >= 0.1.6
  - psutil >= 5.8.0
  - python >= 3.9.0
  - resampy >= 0.2.2
  - scipy >= 1.7.0
  - tqdm >= 4.58.0
  - vtk >= 9.0.1
